server:
   port: 8445
   ssl:
      enabled: true
#     client-auth: need
      key-store: classpath:user-auth-cert.jks
      key-store-password: India330$$
      keyStoreType: JKS
      keyStoreProvider: SUN
      keyAlias: user-auth-cert
      trust-store: classpath:user-auth-cert.jks
      trust-store-password: India330$$
      trust-store-type: JKS
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: https://localhost:${server.port}/info
    healthCheckUrl: https://localhost:${server.port}/health
    homePageUrl: https://localhost:${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/