#server:
#   port: 8445
#   ssl:
#      enabled: true
#     client-auth: need
#      key-store: classpath:user-auth-cert.jks
#      key-store-password: India330$$
#      keyStoreType: JKS
#      keyStoreProvider: SUN
#      keyAlias: user-auth-cert
#      trust-store: classpath:user-auth-cert.jks
#      trust-store-password: India330$$
#      trust-store-type: JKS
eureka:
#  instance:
#    nonSecurePortEnabled: false
#    securePortEnabled: true
#    securePort: ${server.port}
#    statusPageUrl: https://localhost:${server.port}/info
#    healthCheckUrl: https://localhost:${server.port}/health
#    homePageUrl: https://localhost:${server.port}
  client:
#    securePortEnabled: true
    serviceUrl:
#     defaultZone: http://localhost:8761/eureka/
      defaultZone: http://localhost:8080/spring-discovery-service-war/eureka
security:
  oauth2:
    client:
      clientId: USER_CLIENT_APP
      clientSecret: password
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token